### ISSUE TITLE
Heart of Fusion / Roots and Radicals pulsating lights look bad

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#198]
Make these not pulsate; if there's any way to script a global elimination of all pulsating that might be a good idea too.

![Screen Shot 2020-04-01 at 11 08 54 PM](https://user-images.githubusercontent.com/5233345/78229412-ceaa6500-7484-11ea-8759-2c9de3c0f1a3.png)

**Comment by aaronfreed** [comment]
> if there's any way to script a global elimination of all pulsating that might be a good idea too.

I should be able to do this, but it's probably best just to eliminate pulsation for textures that use glow masks; the others should be fine to leave alone. This is only a problem because glow masks don't pulsate at the same rate as the texture proper. Remind me about this if you think it's worth doing.

**Comment by aaronfreed** [comment]
Fixed the pulsating on Roots & Radicals in my latest issue submission; will do likewise with Heart of Fusion when I get around to that level.

**Comment by aaronfreed** [comment]
and here’s the Heart of Fusion fix:

[Heart-of-Fusion.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4442050/Heart-of-Fusion.sceA.zip)

(…edited to fix a couple of untextured walls and a few more bouncy walls I found while playtesting)
