### ISSUE TITLE
Hysterical Womb mistextured floors

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#199]
These ones; check surrounding areas too:

![Screen Shot 2020-04-01 at 11 16 50 PM](https://user-images.githubusercontent.com/5233345/78229479-e71a7f80-7484-11ea-8d6b-2207dc335ef9.png)
![Screen Shot 2020-04-01 at 11 17 14 PM](https://user-images.githubusercontent.com/5233345/78229497-ee418d80-7484-11ea-8af7-e0823457ee8d.png)

**Comment by aaronfreed** [comment]
These should all be fixed:

[Hysterical Womb.zip](https://github.com/Pfhorrest/Eternal/files/4441038/Hysterical.Womb.zip)

This is one thing that’s easier to check in Weland using the “floor textures” display. (Same for ceilings, though I didn’t have time to check those as thoroughly.)

I also rolled back the lightning, since this is not supposed to take place on the Pfhor planet; this also necessitated a change to the Lua file. We’ll also need to modify text resource 128 to remove the ambient sounds for rain on this level, which I’ll do at some later point.

I also added a flickering light to some of the goo in various parts of the level and put in the “transformer” sound in teleporter locations (except the under-the-goo teleporters), which I’m going to make a scenario-wide convention as time permits.
