### ISSUE TITLE
A Friend In Need mistextured sky

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#200]
![Screen Shot 2020-04-01 at 11 29 44 PM](https://user-images.githubusercontent.com/5233345/78229557-031e2100-7485-11ea-9868-97956997af95.png)

**Comment by aaronfreed** [comment]
Fixed. I’ve also set it so there’s a forcefield directly south of the chip insertion point, and inserting the chip turns it off. I’m still not sure if I like this better than how it was (the contrast between the two sky types looked neat, but it makes more story sense for there to be a forcefield there as well); I may revert the behaviour.

It may additionally be worth revising the terminals to make it more explicit where the player is supposed to teleport out, amongst other things. I’ll take a crack at that this weekend, perhaps.

It may actually be worth setting a forcefield to turn *on* when the platform with the formerly mistextured sky finishes rising, just to take it out of the pool of rain polygons. That would require a slight script revision, but shouldn’t be too complicated; I might take a crack at that this weekend as well.

[A Friend in Need.sceA.zip](https://github.com/Pfhorrest/Eternal/files/4441620/A.Friend.in.Need.sceA.zip)

(Rename file if needed – I think I’d renamed my local copy)

…replaced upload because somehow the ambient sounds got messed up; I’ve corrected them so that the polygon sounds & sound objects match again.
