### ISSUE TITLE
Wave Motion Cannon should be more OP again

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#206]
I liked the old OP behavior of pointing haphazardly down a hall and watching everything die better.

**Comment by ravenshining** [comment]
That doesn't happen enough for you now?

Well, IIRC that happened because the radius of the projectile was much larger than it is now.  Large-diameter projectiles tend to get caught on things and stop propagating... And, visually it's weird to have something die when it's not hit by anything.  Together, it makes it seem really buggy.

Three ideas, which may be used on their own or combined:

1) Increase the burst count, primary capacity, and error (the latter to an odd value so one projectile always goes straight ahead), reduce damage accordingly, untick "No horizontal" and "No vertical" error, and, optionally, tick "Horizontal wander" and "Vertical wander."  This will create a wider swath of destruction without being vulnerable to geometry problems.

2) Increase the blast radius and (preferably) add an explosion animation.

3) Lua bounce.  Restore the raidus to something ridiculous, increase the sprite scale to match, and script it so every time it impacts a wall or floor, a new projectile is created at a different angle, until the projectile hits something that *really* should stop it, like a landscape or wall at high angle.

**Comment by Pfhorrest** [comment]
Tripled burst count and capacity, thirded damage accordingly, increased theta to 1 (from 0), allowed error but no wander, and increased projectile radius to 512 (from 384). The last one is what really made it behave as expected again: if I shoot straight ahead at a bunch of skitters (not looking down at them), they still die, as it looks like they should, and accordingly the opening halls of The Dead Live In The Catacombs can be cleared with two shots (one down each), as it looks like they should be.

**Comment by ravenshining** [comment]
Do I recall correctly that you play keyboard-only?  Perhaps that's part of why increasing the radius doesn't cause it to glitch out on you - for a mouse player it will almost never be flying level.

I urge you to consider adding a lua script to allow the projectile to bounce, and at the very least increase the sprite scaling so things won't appear to die for no reason.
