### ISSUE TITLE
Bug-Eyed in Space door should activate only once

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#235]
Check equivalent on Once More Unto The Breach too

![Screen Shot 2020-04-18 at 1 38 00 AM](https://user-images.githubusercontent.com/5233345/79633736-98731380-811b-11ea-8112-197f3414bf42.png)

**Comment by aaronfreed** [comment]
Also, both should be set to “can’t deactivate externally”, which I think might’ve been the real problem here. Will get these when I submit my fixes.

In general, if “activates only once” is set, “can’t deactivate externally” should _always_ be set as well. I can’t think of any case in which you’d want the former and _not_ want the latter – if it’s required to open a door to progress through the game, making it possible to deactivate that door will potentially make the game unwinnable. (I seriously spent an hour just fixing those on “Unwired” for 1.2.) I don’t honestly even know why Bungie made it possible to select that flag set – there’s one door that it’s possible to screw up on “Naw Man He’s Close” that can render a game unwinnable as well.

/rant
