### ISSUE TITLE
Deep into the Grotto should have map annotations

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#242]
The rooms with switches you have to hit should be labelled something like "Data Core #1" (or whatever language is used in the terminals) so cooping players can communicate which ones they've hit already.

**Comment by ravenshining** [comment]
Or single players for that matter!  Yes, the level needs it.  You could set them up so that they aren't visible until someone has hit the terminal... just need a `#TAG` section in the terminal, and lua to 1) detect that the tag has been triggered (possibly via a triggered platform) and 2) reveal a set of polygons with annotations on the automap.

**Comment by Pfhorrest** [comment]
Oh I wasn't thinking of anything that sophisticated, just having regular map annotations inside the rooms so that once you've explored the room you know which of them you've explored, and can communicate with other people about it without lengthy descriptions about "the one in the southwest that you get to by jumping around the one slightly east of it".

**Comment by Pfhorrest** [comment]
This accidentally got un-done in a collision between Aaron's changes and mine.

**Comment by aaronfreed** [comment]
I don't remember when this got fixed again, but in any case, they're in both 1.2.1 and 1.3 (in Latin in the latter case, but since every Latin word has at least one direct English descendant that means basically the same thing, it probably won't be too confusing).
