### ISSUE TITLE
Unwired dancing pfhor

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#260]
Aaron saw a thing here, a fighter "dancing", I don't know what that means:

![Screen Shot 2020-05-11 at 3 29 33 PM](https://user-images.githubusercontent.com/5233345/81629035-0aefb000-93b7-11ea-9361-a31e4c0e8996.png)

**Comment by aaronfreed** [comment]
I think this was just the fighter walking back and forth between two polygons. I have no idea what caused it, since there’s no monster & item impassable polygons in the area apart from the ones on the switch/terminal/pattern buffer, and it probably doesn’t actually need to be fixed for 1.2.1 – I doubt it will even happen for most players, or that they’ll care if it does.
