### ISSUE TITLE
Hysterical Womb misaligned texture

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#269]
Check the other side too:
![Screen Shot 2020-05-11 at 5 03 11 PM](https://user-images.githubusercontent.com/5233345/81629405-e9db8f00-93b7-11ea-994c-c9bb61405501.png)

**Comment by aaronfreed** [comment]
Another one:

![image](https://user-images.githubusercontent.com/8217916/83571663-310bfa00-a4f6-11ea-9c86-c0946bcf35ce.png)

should really be aligned so that the pfhor insignia isn’t split (there’s the same issue on the left side)

this pattern buffer is slightly misaligned:

![image](https://user-images.githubusercontent.com/8217916/83572419-8bf22100-a4f7-11ea-85c7-6980ac37d6ae.png)

and this one, which should also have a higher ceiling:

![image](https://user-images.githubusercontent.com/8217916/83572558-cf4c8f80-a4f7-11ea-9921-f5cb2c69bf8c.png)

(the terminal in the area is also slightly misaligned; not sure if it's a case of it just not being exactly 1 WU wide or if it really is misaligned)

this charger is not exactly 0.5 WU wide so it looks kind of weird

![image](https://user-images.githubusercontent.com/8217916/83572875-5863c680-a4f8-11ea-90bb-fa663b0b5dbf.png)

(is there really any point to these being 2x? there’s 3x in so many other parts of the level that it’s just a matter of how much a player wants to backtrack)

this floor texture somehow wound up mistextured:

![image](https://user-images.githubusercontent.com/8217916/83572927-729da480-a4f8-11ea-87c8-5bc3b2aa550e.png)

the hall on the right is a bit mismatched with the hall on the left, and i'm not sure if the wall to the right is supposed to be a different texture:

![image](https://user-images.githubusercontent.com/8217916/83572989-9e208f00-a4f8-11ea-956e-9db9bb0c94d4.png)

the ceiling above also looks mismatched:

![image](https://user-images.githubusercontent.com/8217916/83573045-ba243080-a4f8-11ea-9231-46068d0311a9.png)

wall textures below cyborg are misaligned:

![image](https://user-images.githubusercontent.com/8217916/83573379-5e0ddc00-a4f9-11ea-8b23-ac0f20862a21.png)

(check other cyborg as well)

goo walls are bouncy:

![image](https://user-images.githubusercontent.com/8217916/83573584-c230a000-a4f9-11ea-8c34-e6a3be0ff06f.png)

(probably just make these ledges solid)

pattern buffer misalignment again:

![image](https://user-images.githubusercontent.com/8217916/83573658-e5f3e600-a4f9-11ea-96e3-47f19cb894f4.png)

pfhor insignia misalignment:

![image](https://user-images.githubusercontent.com/8217916/83573792-1fc4ec80-a4fa-11ea-9b58-d9c7dfc31155.png)

(should the nearby platform make sound? seems kind of strange that it doesn’t, but it might get annoying quickly if it did. could just have the “pfhor platform” sound playing more quietly than normal, emanating from that polygon [not with “is on platform” selected], and eschew start/stop sounds entirely.)

texture here is a bit misaligned:

![image](https://user-images.githubusercontent.com/8217916/83576122-14c08b00-a4ff-11ea-93cd-73a669c64ea4.png)

(issue with the glyph textures being overlaid with the wall textures… of course separating them is going to have its own issues)

other side is slightly off… but close

these have the bottom/top of the light fixture visible at the ceiling/floor boundary:

![image](https://user-images.githubusercontent.com/8217916/83576601-1a6aa080-a500-11ea-8d02-7eefc17924d1.png)

can be fixed with split polys; not sure if worth it

might want these to play the rubicon “power source” (jjaro ship/alien harmonics in rubicon sounds file) sound rather than its “electric hum” sound

sides of this teleporter are textured with goo – is that intentional?

![image](https://user-images.githubusercontent.com/8217916/83576757-73d2cf80-a500-11ea-8969-019c89bef4a5.png)

also it’s way too easy to back up into this mofo on accident; i swear i did it seven times just during this test of the level. maybe raise the floor a bit so players get advance warning they’ve stepped into it

also, too, it should be playing the “transformer” sound, which i’m using for teleporters by convention (however, it’s possible that this has been placed, but there are too many sounds in the area, so it doesn’t get assigned priority)

should the ending terminal graphic actually display a picture of Jason Jones to represent Robert Blake? Maybe if we have a more recent picture of him, since this would presumably be significantly past the events of Marathon 2 (I’m not 100% clear on the timeline though), that would be appropriate to use.

**Comment by aaronfreed** [comment]
Most of these are now fixed, apart from the light fixture in the penultimate screenshot, and the Jason Jones picture. If needed, I can make new issues for those.
