### ISSUE TITLE
Unlucky Pfhor Some badly sized switch

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#271]
I think there are a lot of these, and if we have a scripty way to fix them all that'd be great.

![Screen Shot 2020-05-11 at 5 17 11 PM](https://user-images.githubusercontent.com/5233345/81629493-1db6b480-93b8-11ea-80ab-3ae4f3f6e9d7.png)

**Comment by aaronfreed** [comment]
i'll have to look into how we might find them and export them to a text file, though that'd be the next step after finishing precipitation

other issues on this level:

i thought the “ship creak” sound would be cool, but it feels out of place. play underground explosions or something instead

if i’m not mistaken, this plays the rubicon transformer sound, which we’re using in this era for teleporters. probably should be changed to electric hum, since this really looks like a teleporter:

![image](https://user-images.githubusercontent.com/8217916/83580961-7686f200-a50b-11ea-8da6-8bf2bc40858b.png)

we never did find this phantom hulk, i don’t think:

![image](https://user-images.githubusercontent.com/8217916/83581059-be0d7e00-a50b-11ea-9e29-1b69bc4f3476.png)

![image](https://user-images.githubusercontent.com/8217916/83584041-f913af80-a513-11ea-9bfa-3db913e6c336.png)

monsters that jump down into this area can never climb out. this bob jumped down and now he’s just chillin’

![image](https://user-images.githubusercontent.com/8217916/83581349-8f43d780-a50c-11ea-8413-32cb891e4a61.png)

not sure if it’s worth making a platform they can use or some stairs or something

due to having nowhere to jump, this enforcer never activates unless they get knocked off the ledge:

![image](https://user-images.githubusercontent.com/8217916/83581260-4f7cf000-a50c-11ea-8f64-af1d3808a98c.png)

(that’s right; i’m using gender-neutral pronouns for individual pfhor. we really have no idea what gender most of them are anyway.) i think they’ll need at least two, possibly three polygons they can move on

not sure if it’s just bump maps being weird again but this looks misaligned

![image](https://user-images.githubusercontent.com/8217916/83581405-b6020e00-a50c-11ea-900b-2c9487e632af.png)

its counterpart here is *definitely* misaligned… actually i’m pretty sure all four of these fixtures in this room are misaligned. i’d just check the whole room, giving particular care to the ceiling, which is easy to miss

![image](https://user-images.githubusercontent.com/8217916/83581419-c1553980-a50c-11ea-953b-c3051e72a670.png)

this door got screwed up:

![image](https://user-images.githubusercontent.com/8217916/83581504-fc576d00-a50c-11ea-843e-f36a04daf91d.png)

a couple of these fixtures in this room also have screwy alignment:

![image](https://user-images.githubusercontent.com/8217916/83581543-17c27800-a50d-11ea-8fde-0d15b4ef9e0b.png)

more screwy alignment:

![image](https://user-images.githubusercontent.com/8217916/83581643-6a039900-a50d-11ea-85fd-e3957a0fd0e2.png)

bobs will sometimes just stand around chilling rather than participating in the battle:

![image](https://user-images.githubusercontent.com/8217916/83582056-74726280-a50e-11ea-9ce5-e99e56df7ebc.png)

not sure if there’s an easy way to work around this, since i suspect it’s partially since they’re marked with “stay with clear shot”, which is one of their Things that i wouldn’t really want to change

this Trooper here also never really does anything:

![image](https://user-images.githubusercontent.com/8217916/83582246-07130180-a50f-11ea-8b1b-d5abd3598aa6.png)

they just keep walking in place, which i think might be because all their enemies are out of their firing range. even when i shoot at them, they don’t do anything. i’d replace them with an enforcer maybe. the enforcer would probably be able to snipe pretty effectively from there

more screwy wall alignment:

![image](https://user-images.githubusercontent.com/8217916/83582646-10e93480-a510-11ea-9788-d4938c2b2c71.png)

(check other examples in this room as well again)

and:

![image](https://user-images.githubusercontent.com/8217916/83582466-8f91a200-a50f-11ea-9636-598dc371f87d.png)

and: 

![image](https://user-images.githubusercontent.com/8217916/83582482-9b7d6400-a50f-11ea-9dd6-400ea3dca516.png)

and:

![image](https://user-images.githubusercontent.com/8217916/83582693-30805d00-a510-11ea-9ed7-076fdca97a0a.png)

(i turned infravision on because sometimes it makes it easier to see misalignments)

and:

![image](https://user-images.githubusercontent.com/8217916/83582744-59085700-a510-11ea-869c-4621557cfa62.png)

(actually basically all walls with this texture in this area look like they were never aligned)

and:

![image](https://user-images.githubusercontent.com/8217916/83582820-97057b00-a510-11ea-90e1-94b0ded484b7.png)

this platform’s ambient sound doesn’t play if the player isn’t on the platform:

![image](https://user-images.githubusercontent.com/8217916/83582789-7fc68d80-a510-11ea-91c6-aec83dfa469e.png)

same with its counterpart on the other side of the divide. southern platform is fine though. might just be too many sound objects in area

legit can’t tell for sure if the northeastern and northwestern (not visible in this screenshot) walls here are misaligned, but they look like it:

![image](https://user-images.githubusercontent.com/8217916/83582894-cf0cbe00-a510-11ea-85aa-f80785ba9d30.png)

these don’t line up at all:

![image](https://user-images.githubusercontent.com/8217916/83583095-6b36c500-a511-11ea-8129-3e15f9f40757.png)

i think part of the issue is with the fact that there are multiple textures that are clearly part of the same family, but not actually the same texture… but even so, the grey textures on the left are horribly misaligned

there are some similar problems on the left of the save terminal structure, but not as conspicuously bad:

![image](https://user-images.githubusercontent.com/8217916/83583168-9f11ea80-a511-11ea-9f89-00c505954dda.png)

another misalignment:

![image](https://user-images.githubusercontent.com/8217916/83583231-c668b780-a511-11ea-98de-ec73de584b02.png)

(and other similar cases in the same vicinity)

i think goran just didn’t care that much about texture alignment

should this be “can’t deactivate externally”? it keeps playing its sound if it’s turned off, and it’d trap players in network games if it got turned off at the wrong time, probably

![image](https://user-images.githubusercontent.com/8217916/83583394-3a0ac480-a512-11ea-8b95-ffd437626040.png)

more texture misalignment: (to the left of the compass in this one)

![image](https://user-images.githubusercontent.com/8217916/83583422-5149b200-a512-11ea-94cf-124e08b6820f.png)

![image](https://user-images.githubusercontent.com/8217916/83583758-39266280-a513-11ea-93e8-054505b3171d.png)
(and others in this area – maybe i already flagged this; not sure)

i’d add a pattern buffer here, just because the final battle is intense:

![image](https://user-images.githubusercontent.com/8217916/83584190-5d367380-a514-11ea-8f52-2866a29f8089.png)

i would have these lights play the rubicon power source sound:

![image](https://user-images.githubusercontent.com/8217916/83584287-adadd100-a514-11ea-981d-857f92b7b2b2.png)

also, each set of wires you hit would deactivate the lights for its respective quarter of the light fixture. when all four are inactive, the power source sound turns off. (this could be controlled by the level mission, probably.) maybe we also turn off the force field on the top of the level and start it raining, just in case the game is multiplayer (or a player is insane enough to grenade jump out of that bottom segment… which, after spending about five minutes trying it, i think might theoretically be possible, but you’d have to have grenade jumping in this game down to a science. might be one of those things better done keyboard-only)

**Comment by aaronfreed** [comment]
Almost all of this should be fixed. The power source sound deactivates (well, gets a lot quieter) with each set of wires you turn off, rather than the whole power source, just because that's less of a pain to implement. I also didn't bother with the "turn off the force field idea". Both of those could be 1.4 ideas if we really care about them.

**Comment by Pfhorrest** [comment]
Thanks a bunch!
