### ISSUE TITLE
Eat S'pht mistextured floor

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#287]
![Screen Shot 2020-05-20 at 3 12 08 PM](https://user-images.githubusercontent.com/5233345/82510938-bc31cc80-9ac0-11ea-9965-9c86f3d2ce7a.png)

**Comment by aaronfreed** [comment]
i can't tell if this is misaligned or if it's just a result of bump maps, but double check:

![image](https://user-images.githubusercontent.com/8217916/86429203-dadcd300-bcbc-11ea-9be6-83780ac49ce6.png)

this (same area) is definitely misaligned:

![image](https://user-images.githubusercontent.com/8217916/86429225-ea5c1c00-bcbc-11ea-89ad-beeb7a1c8324.png)

(make sure to align when the platform is down, so the sides of the platform walls get fixed too)

… actually it may be necessary to change some of the textures so this doesn’t happen:
![image](https://user-images.githubusercontent.com/8217916/86430514-7d4a8580-bcc0-11ea-8f0f-5579a3c53cdc.png)

otherwise you get loops that aren’t exactly 1 WU side

more misalignment:

![image](https://user-images.githubusercontent.com/8217916/86429300-25f6e600-bcbd-11ea-8829-104870126660.png)

this above one may take changing some textures in the area to prevent them from wrapping around, possibly

![image](https://user-images.githubusercontent.com/8217916/86429895-cdc0e380-bcbe-11ea-925a-16bc365e7e47.png)

![image](https://user-images.githubusercontent.com/8217916/86429978-14aed900-bcbf-11ea-8bf0-9956c4758d0d.png)

![image](https://user-images.githubusercontent.com/8217916/86430063-46c03b00-bcbf-11ea-9a8d-46d8e951cf2a.png)
and right nearby,
![image](https://user-images.githubusercontent.com/8217916/86430083-52136680-bcbf-11ea-9460-5ab616aa8521.png)

and this, which should maybe be made the vertical equivalent,
![image](https://user-images.githubusercontent.com/8217916/86430120-66effa00-bcbf-11ea-9d4e-d0feffb7772d.png)
(both sides of frame)

even by marathon standards, this light should have an epilepsy warning, or else just be slowed down:
![image](https://user-images.githubusercontent.com/8217916/86430004-28f2d600-bcbf-11ea-9193-95312466ca64.png)

this enforcer just keeps playing their activation sound over and over:
![image](https://user-images.githubusercontent.com/8217916/86430158-838c3200-bcbf-11ea-955e-9684e28c7ab2.png)

lava texture here should play lava sound: 
![image](https://user-images.githubusercontent.com/8217916/86430303-f0073100-bcbf-11ea-94ce-344212ce86ac.png)

more misalignments where you probably need to undo the texture loops to fix them:
![image](https://user-images.githubusercontent.com/8217916/86430376-188f2b00-bcc0-11ea-90e1-5eea2bc5af9d.png)


a note on puzzles. basically, the wires to open up the teleport out of the level don’t open up until you walk on a specific polygon. this is a really annoying puzzle, because there’s nothing indicating that walking on that polygon opened anything up, and the wires are tiny, really easy to miss, and not even visible from the part of the map where they open up. if nothing else, there should at least be a switch to open them up. but if we have them where they currently are, there should be some routing back to the area where the wires are, or some visual cue to signpost the player back that way. right now, it’s just a switch hunt with nothing to tell the player it’s a switch hunt. and when you get there:

![image](https://user-images.githubusercontent.com/8217916/86430664-e03c1c80-bcc0-11ea-80ac-7c75eab4c9c0.png)

you can’t even punch the fuckin’ things. you have to shoot them

i’m not opposed to having a switch hunt to get out of the level, but at least have another switch open up the wires or something

more misalignment i noticed at the last moment:
![image](https://user-images.githubusercontent.com/8217916/86430885-4c1e8500-bcc1-11ea-8e32-5a37935c3b72.png)
(invincibility turned on to screenshot safely)

![image](https://user-images.githubusercontent.com/8217916/86430937-6bb5ad80-bcc1-11ea-954e-279c9cf6e5ed.png)

these pfhor teleported in above the ceiling:
![image](https://user-images.githubusercontent.com/8217916/86431278-673dc480-bcc2-11ea-8067-9f99a733b6fc.png)

(went back to confirm i wasn't seeing things, and yep, they teleported in above the ceiling. hard to get a screenshot of though)

misaligned?
![image](https://user-images.githubusercontent.com/8217916/86431339-90f6eb80-bcc2-11ea-8a1b-5eb89dd09ed1.png)

**Comment by aaronfreed** [comment]
All fixed, with the possible exception of the flow – this might just need to be addressed by writing a cursory terminal, as Rich’s maps just tended to flow in rather unusual ways, and it doesn’t help that I stitched the current revision together from two different iterations of the map. Speaking of which, there remain a bunch of issues with the texturing in the areas I imported from “Eve of Orbit”; I will fix these in due course.
