### ISSUE TITLE
Bug-Eyed In Space extermination problems

### ISSUE THREAD

**Issue by Pfhorrest** [Pfhorrest/Eternal#294]
You have to kill some hulks to complete the mission. That should not be required.

**Comment by aaronfreed** [comment]
Apparently this can be fixed by unsetting the “alien” flags in the physics. Which I kind of agree with anyway – allies probably shouldn’t have it set.

**Comment by aaronfreed** [comment]
This level (and Once More unto the Breach) are no longer technically extermination missions, since some monsters that start out the level hostile become friendly over the course of the level due to Lua scripting (this is a story change in 1.3). It's still necessary to kill most of the Pfhor, though. (You can leave as many as three alive; I implemented this by activating a platform that controls a repair switch in an inaccessible part of the level once no more than three Pfhor still survive.)

1.2.1 fixes this in a different way, by unmarking the "alien" flag for the Hulks in the physics when they're friendly. In both cases, this is no longer an issue.
