### ISSUE TITLE
Terminal on The Ensurance Trap is super non-obvious

### ISSUE THREAD

**Issue by ravenshining** [Pfhorrest/Eternal#81]
Every time you go through the failure dream, you pass a fake terminal.  But, in Chapter 4, it's active, and there's no reason to expect it to be.

The terminal should be darkened or absent on other levels, and lit on The Ensurance Trap, so people know to read it.

**Comment by Pfhorrest** [comment]
I'm thinking of instead maybe splitting up the end-terminals of the other levels so that there's always something on this terminal.

Partly because I'm considering turning the prologue level into a dream, set on this same geometry, and splitting up the super-long prologue terminal between the first terminal and this middle terminal, accomplishing several things at once.

**Comment by Pfhorrest** [comment]
Nope, just made that one terminal light dependent like you suggested. It also controls the door now, so you have to read it.
